### ISSUE TITLE
In Redmine version 6.0.0, the current theme appears to be broken.

### ISSUE THREAD

**Issue by jaebokoh** [HolonGlobe/PurpleMine2#284]
In Redmine version 6.0.0, the current theme appears to be broken.

<img width="1478" alt="image" src="https://github.com/user-attachments/assets/1591dc80-1488-4ecf-9849-21126aff452a">

**Comment by Shanti9** [comment]
Yes, same here! I have returned to 5.1.4 until this is resolved. Is there a plan to make PurpleMine compatible with Redmine 6?

**Comment by Grovkillen** [comment]
Yeah, same for me. I guess the move from

-/public/themes/*
-!/public/themes/alternate
-!/public/themes/classic
-!/public/themes/README

to

+/app/assets/themes/*
+!/app/assets/themes/alternate
+!/app/assets/themes/classic
+!/app/assets/themes/README

Really messed things up. I tried to just change the path in the themes application.css file but it's not pointing to the correct path once deployed.

https://www.redmine.org/issues/39111

**Comment by Grovkillen** [comment]
I got it somewhat to work by adding this to my nginx.config file:

```
# Needed MIME-types
types {
	text/css css;
	application/javascript js;
}

# CSS files
location ~ ^/assets/themes/(.+?)/(.+?)\.css$ {
	alias /usr/share/redmine/themes/$1/stylesheets/$2.css;
	access_log off;
	expires max;
}

# JavaScript files
location ~ ^/assets/themes/(.+?)/(.+?)\.js$ {
	alias /usr/share/redmine/themes/$1/javascripts/$2.js;
	access_log off;
	expires max;
}

# favicon files
location ~ ^/assets/themes/(.+?)/favicon.ico$ {
	alias /usr/share/redmine/themes/$1/favicon/favicon.ico;
	access_log off;
	expires max;
}

# font files
location ~ ^/assets/themes/fonts/(.+?)\.([^?]+?)$ {
	alias /usr/share/redmine/themes/fonts/$1.$2;
	access_log off;
	expires max;
}

# images files
location ~ ^/assets/themes/(.+?)/images/(.+?)\.(.+?)$ {
	alias /usr/share/redmine/themes/$1/images/$2.$3;
	access_log off;
	expires max;
}

# svg files
location ~ ^/assets/themes/(.+?)/svg/(.+?)\.(.+?)$ {
	alias /usr/share/redmine/themes/$1/svg/$2.$3;
	access_log off;
	expires max;
}
```

And moved all the code from application.css into a theme.css file. All the default css code from the Redmine application.css file copied to a file I named default.css. The new application.css file have this inside:

```
@import url(./default.css);
@import url(./theme.css);
```

And lastly I moved the fonts folder directly under the themes folder.

![image](https://github.com/user-attachments/assets/ba063536-3744-4922-bbeb-6df22f48cbbd)

**Comment by Shanti9** [comment]
That's a great hack @Grovkillen! But was it not simpler to just redistribute Purplemine assets so that file paths accommodate to Redmine 6 requirements? As not everyone has access or convenience of editing nginx conf...

**Comment by Grovkillen** [comment]
Yeah, I just wanted to get my installation working but I do agree that the Redmine team need to think about the way they intend this new structure.

**Comment by BFjimmy** [comment]
Just to add. The new Redmine interface uses SVG files for these elements. I had to remove them by adding this to the theme file:

```
a > svg,
span > svg,
legend > svg {
    display: none;
}
```

**Comment by BFjimmy** [comment]
Also added these:

```
a > svg,
span > svg,
legend > svg,
.icon > svg,
div > svg {
  display: none;
}
```

**Comment by fishermans** [comment]
This is my proxy config, running redmine on sub uri .../redmine on docker. It also needs further tuning like config.ru settings.

Not even the purple mine theme is looking as shown above but also the additional themes are broken. I told that to the redmine team before v6 came out but they have not change it, yet. 

```

# the regex logic: after either /javascripts/ or /stylesheets/ find the suffixes we want, followed by one or more numbers 0-9
# This works because the files we want to cache always appear after one of those 2 directories:  but not the files we want to ignore
# /journals/edit/24174.js  and /uploads.js?attachment_id=1&filename=my-file-to-upload.png
location ~* /redmine(?<file>/(?:(?:plugin_assets|themes).+)?(?:javascripts|stylesheets|images|favicon).+(?:css|js|jpe?g|gif|ico|png|html)(\?[0-9]+)$) {

    expires 24h;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript text/html;

    try_files $file @redmine;
    break;
}

location ^~ /redmine {
    ## Serve static files from defined root folder.
    ## @redmine is a named location for the upstream fallback, see below.
    try_files $uri index.html $uri.html @redmine;
}

# Fix for Redmine 6.0.0 since sub uri is not totally supported, yet.
location ^~ /assets/ {
    rewrite ^/assets/(.*)$ /redmine/assets/$1 break;
    try_files $uri index.html $uri.html @redmine;
}

## If a file, which is not found in the root folder is requested,
## then the proxy passes the request to the upsteam (redmine unicorn).
location @redmine {
    #Set backend server
    #set $redmine_back redmine:3000;
    set $redmine_back unix:/var/redmine/sockets/redmine.sock;

    # Enable proxy caching
    proxy_cache redmine_cache;
    proxy_cache_revalidate on;
    proxy_cache_min_uses 3;
    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
    proxy_cache_background_update on;
    proxy_cache_lock on;
    proxy_cache_bypass $cookie_nocache $arg_nocache $http_pragma;

    # Cache valid responses
    proxy_cache_valid 301 999m;
    proxy_cache_key "$scheme://$host$request_uri";
    proxy_ignore_headers X-Accel-Expires Expires Cache-Control;

    ## If you use HTTPS make sure you disable gzip compression
    ## to be safe against BREACH attack.
    # gzip off;

    ## Some requests take more than 30 seconds.
    proxy_read_timeout      300;
    proxy_connect_timeout   300;
    proxy_redirect          off;

    proxy_pass http://$redmine_back;
}

````

**Comment by Grovkillen** [comment]
Yes, the Redmine team seems a bit off regarding this. But on the other hand, I haven't found any reports about it. And also, the sub-uri integration isn't very straight forward as you mention @fishermans

**Comment by Grovkillen** [comment]
I've found an issue report here: https://www.redmine.org/issues/41754

**Comment by Plinsboorg** [comment]
Hi all, 
I'm not a programmer myself, but I can ask for external help. 
But first I need to understand where the problem of these big icons comes from. 
Is this something that can be fixed by modifying the theme repo itself?
Or is it not possible, and redmine maintainers need to change something on their end first?

**Comment by fishermans** [comment]
> Hi all, I'm not a programmer myself, but I can ask for external help. But first I need to understand where the problem of these big icons comes from. Is this something that can be fixed by modifying the theme repo itself? Or is it not possible, and redmine maintainers need to change something on their end first?

The reason is that some data are not found by the browser. If you hit F12 in Chrome, you will see that some js / css files are not found. The location for themes and the way how it is handled has changed in v6.

As @Grovkillen pointed out there is an issue logged. I did not try it again since I am still on v5.1.

Maybe it needs some further modifications to your Apache / nginx configuration if your instance is behind a proxy. I am using nginx and added some lines (see above) to fix the missing data.

In short, if all data are found by the browser the icon will appear in the expected size.

**Comment by Grovkillen** [comment]
6.0.2 should fix this but I haven't tried it myself since I fixed it by
adding a custom CSS file.

Den fre 3 jan. 2025 21:11fishermans ***@***.***> skrev:

**Comment by fishermans** [comment]
The patch attached to this ticket is only adding some information to the documentation.

**Comment by Plinsboorg** [comment]
I just run Redmine 6.0.2.stable in docker and I can still see this issue with PurpleMine theme. 
But I only tested on localhost.

**Comment by alemeilleur** [comment]
Same pb (with Apache2) ...

**Comment by kozmotronik** [comment]
> 6.0.2 should fix this but I haven't tried it myself since I fixed it by
> adding a custom CSS file.
> 
> Den fre 3 jan. 2025 21:11fishermans ***@***.***> skrev:
> […](#)

I've tested it with Redmine v6.0.3. It is still broken. I am still looking forward to use this theme for my Redmine instance. Hope it get updated for v6.0 soon.

**Comment by christophwolff** [comment]
Any news?

**Comment by alpodsypanin** [comment]
I have the same problem.
Redmine version                6.0.3.stable
But this 
https://github.com/farend/redmine_theme_farend_bleuclair
theme is working correctly. Or Circle and A1 from RedmineUp.

**Comment by HThanh-how** [comment]
> adding a custom CSS file.

please help me, what u add into css file. Can u share for me. Thank u

**Comment by Grovkillen** [comment]
> please help me, what u add into css file. Can u share for me. Thank u

Here's my custom CSS file but please observe that the colors etc. are also part of this file. Pick your stuff from it.

```
.icon-email-add,
.icon-passwd,
.cf_35,
.cf_36,
.cf_21,
a > svg,
span > svg,
legend > svg,
.icon > svg,
div > svg,
.projects .root div.wiki.description,
.modal,
p:has(> #project_default_version_id) {
  display: none !Important;
}

.ui-widget-header,
.modal {
    z-index: 11000 !Important;
}

#project-jump .drdn-content {
    z-index: 10001 !Important;
}

.tribute-container {
 height: 300px !Important;
 max-height: 300px;
}

.like-icon-outer {
  margin-top: -20px;
}

.like-icon-outer {
  margin-bottom: 15px;
}

.like-side-by-side > p {
  margin: 0;
  padding: 0;
}

[id^="heart-on-"] {
  color: #beb500 !Important;
}

[id^="heart-off-"] {
  color: grey !Important;
}

.like-sender-tooltip:hover .like-sender-content {
  top: -5px !Important;
  z-index: 10001;
}

.like-sender-content:before {
  top:2px !Important;
}

.likes-incoming-header-user-wiki,
.likes-outgoing-header-user-wiki,
.likes-incoming-wiki,
.likes-outgoing-wiki {
  display:none;
}

.user-mention {
    display: inline-block;
    padding: 2px 6px;
    background-color: rgba(0, 120, 255, 0.1);
    color: #0078ff;
    font-weight: bold;
    border-radius: 4px;
    text-decoration: none;
    transition: background-color 0.2s ease-in-out;
}

.user-mention:hover {
    background-color: rgba(0, 120, 255, 0.1);
}

.tags.attribute > .label.tag_label {
  display: none;
}

.tags.attribute {
  padding-left:0 !Important;
}

#tag_click {
  display:none;
}

#ajax-indicator {
    z-index: 12000 !Important;
}

.webforms::before {
  padding-right: 7px !Important;
}

.members .label {
  font-weight: bold;
}

#browser .group-header button {
   display: block;
}
.controller-repositories span:first-child {
    text-align: left !important;
}

.flyout-menu .dashboard-system-default {
    height: 1.5em;
    width: 1.5em;
    transform: translateY(-31px);
}

.wiki.project-description {
  padding-bottom: 20px;
}

.select2-container.select2-container--default {
  z-index: 9998;
  max-width: 100%;
}

.ui-tooltip{
  z-index: 9999 !Important;
}

a.icon.assign-to-me {
  margin-left: -15px !Important;
}

a.icon.assign-to-me > svg {
  display: inline !Important;
  stroke: #00a5a3;
  width: 15px;
  height: 15px;
  margin-bottom: -3px !Important;
  border: solid 1px;
  border-radius: 3px;
}

input[type="checkbox"]:disabled {
    cursor: not-allowed !Important;
}

input[type="checkbox"][name="checklist_item"] {
    cursor: pointer;
}

/* Justera endast select2-selection__arrow som syskon till #month eller #year */
#month ~ .select2-container span.select2-selection__arrow,
#year ~ .select2-container span.select2-selection__arrow {
    top: 4px;
    right: 0px;
    width: 33px;
}

#month ~ span.select2-container {
    width: unset !Important;
}

.gototop {
    position: fixed;
    bottom: 20px;
    right: 20px;
    text-align: right;
    padding: 10px;
    background: rgba(255, 255, 255, 0.5);
    border-radius: 5px;
    transition: all 0.3s ease-in-out;
    opacity: 0.1;
}

.gototop a {
    display: inline-block;
    color: #333;
    text-decoration: none;
}

.gototop:hover {
    opacity: 1;
    pointer-events: auto;
}

.gototop a:hover {
    color: #007bff;
}

div.mermaid svg {
  display: unset;
}

a.icon.icon-page-up {
  position: relative;
}

a.icon.icon-page-up > svg {
  position: absolute;
  display: unset;
  left: 4px;
  width: 20px;
  height: 20px;
}

tr.project.idnt-1 td.name {
    background-position: 5px 9px;
}

.select2-container.select2-container--default.select2-container--open .select2-selection,
.select2-container.select2-container--default.select2-container--focus .select2-selection {
    box-shadow: inset 0 1px 2px rgba(0, 0, 0, .075), 0 0 0 2px #beb500;
}

#sidebar .dashboards .dashboard-system-default {
    height: 20px;
    position: absolute;
    transform: translateY(-26px);
}

#issue_tracker_id:has(option:only-of-type),
#issue_status_id:has(option:only-of-type) {
    background-color: #e9e9e9;
    color: #6c757d;
}

#checklist-menu a:hover {
    color: #ffffff !Important;
}

#issue_statuses_description dt {
    margin: 0 0 5px;
}

#issue_statuses_description dd {
    margin-right: 0;
    margin-left: 0;
}

#checklist-menu {
   font-size: unset;
}

#checklist-menu li {
    padding: unset !Important;
    border: unset !Important;
}

.ui-state-active,
.ui-widget-content .ui-state-active {
    background-color: #beb500;
}

#projects-index ul.projects a.project.child {
    font-size: 1em;
}

.drdn.expanded>.drdn-content {
    white-space: nowrap;
}

ul.projects {
    padding-left: 8px;
}

#tracker_project_ids>ul {
    max-height: unset;
}

#loggedas > a.user.active {
  text-transform: lowercase;
}

li:has(> a#tab-versions),
li:has(> a.new-version),
li:has(> a.register),
span:has(> a.atom),
p.other-formats {
    display: none; /* Göm <p> som standard */
}

p.other-formats:has(span:only-child > a.atom) {
    display: none; /* Göm endast om <p> innehåller exakt en <span> med en child <a class="atom"> */
}

p.other-formats:has(:not(:only-child)) {
    display: block; /* Visa <p> om den har fler än ett child-element */
}

.button-login {
    display: block;
    margin: 0 auto;
    padding: 6px;
    width: 295px;
}

a,
a.icon,
a.icon-only,
a.collapsible,
.collapsible > legend,
div.tabs:not(#main-menu)>ul>li>a {
  color: #212136;
}

a:hover,
a:focus,
a.icon:focus,
a.icon:hover,
a.icon-only:focus,
a.icon-only:hover,
a.collapsible:hover,
a.collapsible:focus,
a.collapsible.icon:hover,
a.collapsible.icon:focus,
.collapsible>legend:hover,
.collapsible>legend:focus {
  color: #beb500;
  text-decoration: none;
}

button.ui-dialog-titlebar-close::after {
  content: "\00D7";
  display: inline-block;
  position: absolute;
  left: 3px;
  top: -6px;
  color: #fff;
  font-size: 1.3em;
}

li.select2-results__option--highlighted[role="option"][aria-selected] {
    background-color: #beb500 !Important;
    color: #fff !Important;
}

.ui-widget-header button.ui-button {
  background-color: #C61035;
  border-color: #C61035;
  color: transparent;
  text-indent: unset;
}

.ui-widget-header button.ui-button:hover {
  background-color: #A50928;
  border-color: #770920;
}

.contextual .drdn-items {
    padding: unset;
}

.contextual:not(.journal-actions) > .drdn.expanded>.drdn-trigger {
  border-color: #989100;
  background-color: #beb500;
  color: #fff;
}

.context-menu-selection a,
.context-menu-selection a:hover {
  color: #212136;
}

div > input[type=radio],
div > input[type=checkbox] {
    margin: 7px 3px 0 5px;
}

div.filter {
  display: flex;
}

div.filter > div {
  margin-right: 5px;
}

table.list td.login {
    text-align: left;
}

.ui-widget-header,
#header,
#main-menu .menu-children a:hover,
#main-menu .menu-children a:focus,
#project-jump a:hover,
#project-jump a:focus {
  background-color: #beb500;
}

#wrapper .context-menu-selection,
#wrapper .context-menu-selection>td {
    background-color: #beb500 !important;
    color: #fff !important;
}

#context-menu {
 padding: 2px 10px 10px 22px !Important;
}

#context-menu > ul {
  border:none !Important;
}

#context-menu ul ul {
  width: max-content;
  max-width:300px;
}

#context-menu.reverse-x li.folder>ul {
    right: 149px !Important;
}

#context-menu .icon::before {
    margin-left: -25px;
}

#context-menu .custom-icon-for-context-menu {
  display: inline !Important;
  position: absolute;
  top: 4px;
  fill: #beb500;
}

#context-menu .disabled .icon-label {
  margin-left:20px;
}

#context-menu .icon-copy .icon-label,
#context-menu .icon-del .icon-label {
  margin-left:6px;
}

#context-menu li:hover {
    border: 1px solid #beb500 !Important;
    background-color: #beb5006b !Important;
}

#context-menu li.folder::before {
    content: "◀";
    font-size: 14px;
    margin-top: 1px;
    margin-right: 6px;
    display: inline-block;
    color: #000;
}

#context-menu li a.submenu {
    background: none !Important;
    padding-left: 2px !Important;
}

#top-menu {
  background-color: #beb500;
  border-bottom: 1px solid #989100;
  color: #ffffff;
}

#top-menu a {
  color: #000000;
}

#main-menu>ul>li>a.selected {
    border-bottom: 3px solid #beb500;
}

select:focus,
textarea:focus,
input[type=datetime]:focus,
input[type=datetime-local]:focus,
input[type=date]:focus,
input[type=month]:focus,
input[type=time]:focus,
input[type=week]:focus,
input[type=number]:focus,
input[type=url]:focus,
input[type=tel]:focus,
input[type=color]:focus,
input[type=search]:focus,
input[type=email]:focus,
input[type=text]:focus,
input[type=password]:focus {
    border-color: rgba(167,159,0, .6);
    box-shadow: inset 0 1px 2px rgba(0, 0, 0, .075), 0 0 0 2px rgba(167,159,0, .2);
}

input[type=button],
input[type=submit],
input[type=reset],
button {
    background-color: #029934;
    color: #fff;
    border-color: #029934 #029934 #027b2a;
    box-shadow: 0 1px 0 #027b2a;
}

input[type=button]:hover,
input[type=button]:focus,
input[type=submit]:hover,
input[type=submit]:focus,
input[type=reset]:hover,
input[type=reset]:focus,
button:hover,
button:focus {
    background-color: #027b2a;
    color: #fff;
    border-color: #027b2a #027b2a #015d1f;
    box-shadow: 0 1px 0 #015d1f;
}

form input[type=submit]+input {
    background-color: #a3a6b7;
    color: #fff;
    border-color: #a3a6b7 #a3a6b7 #5d6560;
    box-shadow: 0 1px 0 #ababab;
}

form input[type=submit]+input:hover,
form input[type=submit]+input:focus {
    background-color: #5d6560;
    color: #fff;
    border-color: #5d6560 #5d6560 #010101;
    box-shadow: 0 1px 0 #015d1f;
}

p.legend.cal > span {
  display: flex;
}

.issue.details>.subject,
.issue.details>.author {
    padding-left: unset;
}

.issue.details {
    margin-top: 5px;
}

#login-form {
  display: none;
}

#list-definition > div {
  display: flex;
  margin-bottom: 5px;
}

#list-definition > div > div {
  display: inline-grid;
  margin-right: 5px;
}

#list-definition > div > div.buttons {
  margin-top: auto;
  margin-bottom: auto;
}

#list-definition input[type="button"]:not(:first-child) {
  margin-top: 5px; /* Mellanrum för alla utom den första */
}

#query_form_with_buttons > p.buttons > select {
  margin-bottom: 5px;
}

li.ui-menu-item:hover {
  background-color: #beb500 !Important;
}

.ui-tooltip-content {
  color: unset !Important;
}
.ui-tooltip {
  box-shadow: unset !Important;
}


/* Ticket type colors */
tr.tracker-1 .id > a,
tr.tracker-1 .issue_id > a,
a.tracker-1.issue,
a.tracker-1,
.relations > span > a.tracker-1,
.parent>a.tracker-1 {
/*
    background-color: #e5123d;
    color: #fff;
*/
}

tr.tracker-1 .id > a:hover,
tr.tracker-1 .issue_id > a:hover,
a.tracker-1.issue:hover,
a.tracker-1:hover,
.relations > span > a.tracker-1:hover,
.parent > a.tracker-1:hover {
/*
    background-color: #e5123d;
    color: #fff;
*/
}

label.error {
  color: #000;
  text-shadow: 0 0 5px rgba(255, 0, 0, 0.8);
  animation: pulseShadow 1s infinite;
}

/* Definiera keyframes för animationen */
@keyframes pulseShadow {
  0%, 100% {
    text-shadow: 0 0 5px rgba(255, 0, 0, 0.8);
  }
  50% {
    text-shadow: 0 0 15px rgba(255, 0, 0, 1);
  }
}

@media screen and (max-width: 899px) {
    body #header {
        background-color: #beb500;
    }
}

@media screen and (max-width: 899px) {
    body .flyout-menu {
        background-color: #989100;
        color: #fff;
    }
}

@media screen and (max-width: 899px) {
    .flyout-menu {
        background-color: #706B02;
    }
}

@media screen and (max-width: 899px) {
    body .flyout-menu h3, body .flyout-menu h4 {
        border-top: 1px solid #706B02;
        border-bottom: 1px solid #706B02;
        background-color: #706B02;
    }
}
```

**Comment by ricardon85** [comment]
Just add to the theme's application.css file the code below.
```
svg.s12, svg.s14, svg.s18, svg.s20{
    display: none;
}
```

**Comment by alpodsypanin** [comment]
> Just add to the theme's application.css file the code below.
> 
> ```
> svg.s12, svg.s14, svg.s18, svg.s20{
>     display: none;
> }
> ```

Thank you!

**Comment by HThanh-how** [comment]
> > please help me, what u add into css file. Can u share for me. Thank u
> 
> Here's my custom CSS file but please observe that the colors etc. are also part of this file. Pick your stuff from it.
> 
> ```
> .icon-email-add,
> .icon-passwd,
> .cf_35,
> .cf_36,
> .cf_21,
> a > svg,
> span > svg,
> legend > svg,
> .icon > svg,
> div > svg,
> .projects .root div.wiki.description,
> .modal,
> p:has(> #project_default_version_id) {
>   display: none !Important;
> }
> 
> .ui-widget-header,
> .modal {
>     z-index: 11000 !Important;
> }
> 
> #project-jump .drdn-content {
>     z-index: 10001 !Important;
> }
> 
> .tribute-container {
>  height: 300px !Important;
>  max-height: 300px;
> }
> 
> .like-icon-outer {
>   margin-top: -20px;
> }
> 
> .like-icon-outer {
>   margin-bottom: 15px;
> }
> 
> .like-side-by-side > p {
>   margin: 0;
>   padding: 0;
> }
> 
> [id^="heart-on-"] {
>   color: #beb500 !Important;
> }
> 
> [id^="heart-off-"] {
>   color: grey !Important;
> }
> 
> .like-sender-tooltip:hover .like-sender-content {
>   top: -5px !Important;
>   z-index: 10001;
> }
> 
> .like-sender-content:before {
>   top:2px !Important;
> }
> 
> .likes-incoming-header-user-wiki,
> .likes-outgoing-header-user-wiki,
> .likes-incoming-wiki,
> .likes-outgoing-wiki {
>   display:none;
> }
> 
> .user-mention {
>     display: inline-block;
>     padding: 2px 6px;
>     background-color: rgba(0, 120, 255, 0.1);
>     color: #0078ff;
>     font-weight: bold;
>     border-radius: 4px;
>     text-decoration: none;
>     transition: background-color 0.2s ease-in-out;
> }
> 
> .user-mention:hover {
>     background-color: rgba(0, 120, 255, 0.1);
> }
> 
> .tags.attribute > .label.tag_label {
>   display: none;
> }
> 
> .tags.attribute {
>   padding-left:0 !Important;
> }
> 
> #tag_click {
>   display:none;
> }
> 
> #ajax-indicator {
>     z-index: 12000 !Important;
> }
> 
> .webforms::before {
>   padding-right: 7px !Important;
> }
> 
> .members .label {
>   font-weight: bold;
> }
> 
> #browser .group-header button {
>    display: block;
> }
> .controller-repositories span:first-child {
>     text-align: left !important;
> }
> 
> .flyout-menu .dashboard-system-default {
>     height: 1.5em;
>     width: 1.5em;
>     transform: translateY(-31px);
> }
> 
> .wiki.project-description {
>   padding-bottom: 20px;
> }
> 
> .select2-container.select2-container--default {
>   z-index: 9998;
>   max-width: 100%;
> }
> 
> .ui-tooltip{
>   z-index: 9999 !Important;
> }
> 
> a.icon.assign-to-me {
>   margin-left: -15px !Important;
> }
> 
> a.icon.assign-to-me > svg {
>   display: inline !Important;
>   stroke: #00a5a3;
>   width: 15px;
>   height: 15px;
>   margin-bottom: -3px !Important;
>   border: solid 1px;
>   border-radius: 3px;
> }
> 
> input[type="checkbox"]:disabled {
>     cursor: not-allowed !Important;
> }
> 
> input[type="checkbox"][name="checklist_item"] {
>     cursor: pointer;
> }
> 
> /* Justera endast select2-selection__arrow som syskon till #month eller #year */
> #month ~ .select2-container span.select2-selection__arrow,
> #year ~ .select2-container span.select2-selection__arrow {
>     top: 4px;
>     right: 0px;
>     width: 33px;
> }
> 
> #month ~ span.select2-container {
>     width: unset !Important;
> }
> 
> .gototop {
>     position: fixed;
>     bottom: 20px;
>     right: 20px;
>     text-align: right;
>     padding: 10px;
>     background: rgba(255, 255, 255, 0.5);
>     border-radius: 5px;
>     transition: all 0.3s ease-in-out;
>     opacity: 0.1;
> }
> 
> .gototop a {
>     display: inline-block;
>     color: #333;
>     text-decoration: none;
> }
> 
> .gototop:hover {
>     opacity: 1;
>     pointer-events: auto;
> }
> 
> .gototop a:hover {
>     color: #007bff;
> }
> 
> div.mermaid svg {
>   display: unset;
> }
> 
> a.icon.icon-page-up {
>   position: relative;
> }
> 
> a.icon.icon-page-up > svg {
>   position: absolute;
>   display: unset;
>   left: 4px;
>   width: 20px;
>   height: 20px;
> }
> 
> tr.project.idnt-1 td.name {
>     background-position: 5px 9px;
> }
> 
> .select2-container.select2-container--default.select2-container--open .select2-selection,
> .select2-container.select2-container--default.select2-container--focus .select2-selection {
>     box-shadow: inset 0 1px 2px rgba(0, 0, 0, .075), 0 0 0 2px #beb500;
> }
> 
> #sidebar .dashboards .dashboard-system-default {
>     height: 20px;
>     position: absolute;
>     transform: translateY(-26px);
> }
> 
> #issue_tracker_id:has(option:only-of-type),
> #issue_status_id:has(option:only-of-type) {
>     background-color: #e9e9e9;
>     color: #6c757d;
> }
> 
> #checklist-menu a:hover {
>     color: #ffffff !Important;
> }
> 
> #issue_statuses_description dt {
>     margin: 0 0 5px;
> }
> 
> #issue_statuses_description dd {
>     margin-right: 0;
>     margin-left: 0;
> }
> 
> #checklist-menu {
>    font-size: unset;
> }
> 
> #checklist-menu li {
>     padding: unset !Important;
>     border: unset !Important;
> }
> 
> .ui-state-active,
> .ui-widget-content .ui-state-active {
>     background-color: #beb500;
> }
> 
> #projects-index ul.projects a.project.child {
>     font-size: 1em;
> }
> 
> .drdn.expanded>.drdn-content {
>     white-space: nowrap;
> }
> 
> ul.projects {
>     padding-left: 8px;
> }
> 
> #tracker_project_ids>ul {
>     max-height: unset;
> }
> 
> #loggedas > a.user.active {
>   text-transform: lowercase;
> }
> 
> li:has(> a#tab-versions),
> li:has(> a.new-version),
> li:has(> a.register),
> span:has(> a.atom),
> p.other-formats {
>     display: none; /* Göm <p> som standard */
> }
> 
> p.other-formats:has(span:only-child > a.atom) {
>     display: none; /* Göm endast om <p> innehåller exakt en <span> med en child <a class="atom"> */
> }
> 
> p.other-formats:has(:not(:only-child)) {
>     display: block; /* Visa <p> om den har fler än ett child-element */
> }
> 
> .button-login {
>     display: block;
>     margin: 0 auto;
>     padding: 6px;
>     width: 295px;
> }
> 
> a,
> a.icon,
> a.icon-only,
> a.collapsible,
> .collapsible > legend,
> div.tabs:not(#main-menu)>ul>li>a {
>   color: #212136;
> }
> 
> a:hover,
> a:focus,
> a.icon:focus,
> a.icon:hover,
> a.icon-only:focus,
> a.icon-only:hover,
> a.collapsible:hover,
> a.collapsible:focus,
> a.collapsible.icon:hover,
> a.collapsible.icon:focus,
> .collapsible>legend:hover,
> .collapsible>legend:focus {
>   color: #beb500;
>   text-decoration: none;
> }
> 
> button.ui-dialog-titlebar-close::after {
>   content: "\00D7";
>   display: inline-block;
>   position: absolute;
>   left: 3px;
>   top: -6px;
>   color: #fff;
>   font-size: 1.3em;
> }
> 
> li.select2-results__option--highlighted[role="option"][aria-selected] {
>     background-color: #beb500 !Important;
>     color: #fff !Important;
> }
> 
> .ui-widget-header button.ui-button {
>   background-color: #C61035;
>   border-color: #C61035;
>   color: transparent;
>   text-indent: unset;
> }
> 
> .ui-widget-header button.ui-button:hover {
>   background-color: #A50928;
>   border-color: #770920;
> }
> 
> .contextual .drdn-items {
>     padding: unset;
> }
> 
> .contextual:not(.journal-actions) > .drdn.expanded>.drdn-trigger {
>   border-color: #989100;
>   background-color: #beb500;
>   color: #fff;
> }
> 
> .context-menu-selection a,
> .context-menu-selection a:hover {
>   color: #212136;
> }
> 
> div > input[type=radio],
> div > input[type=checkbox] {
>     margin: 7px 3px 0 5px;
> }
> 
> div.filter {
>   display: flex;
> }
> 
> div.filter > div {
>   margin-right: 5px;
> }
> 
> table.list td.login {
>     text-align: left;
> }
> 
> .ui-widget-header,
> #header,
> #main-menu .menu-children a:hover,
> #main-menu .menu-children a:focus,
> #project-jump a:hover,
> #project-jump a:focus {
>   background-color: #beb500;
> }
> 
> #wrapper .context-menu-selection,
> #wrapper .context-menu-selection>td {
>     background-color: #beb500 !important;
>     color: #fff !important;
> }
> 
> #context-menu {
>  padding: 2px 10px 10px 22px !Important;
> }
> 
> #context-menu > ul {
>   border:none !Important;
> }
> 
> #context-menu ul ul {
>   width: max-content;
>   max-width:300px;
> }
> 
> #context-menu.reverse-x li.folder>ul {
>     right: 149px !Important;
> }
> 
> #context-menu .icon::before {
>     margin-left: -25px;
> }
> 
> #context-menu .custom-icon-for-context-menu {
>   display: inline !Important;
>   position: absolute;
>   top: 4px;
>   fill: #beb500;
> }
> 
> #context-menu .disabled .icon-label {
>   margin-left:20px;
> }
> 
> #context-menu .icon-copy .icon-label,
> #context-menu .icon-del .icon-label {
>   margin-left:6px;
> }
> 
> #context-menu li:hover {
>     border: 1px solid #beb500 !Important;
>     background-color: #beb5006b !Important;
> }
> 
> #context-menu li.folder::before {
>     content: "◀";
>     font-size: 14px;
>     margin-top: 1px;
>     margin-right: 6px;
>     display: inline-block;
>     color: #000;
> }
> 
> #context-menu li a.submenu {
>     background: none !Important;
>     padding-left: 2px !Important;
> }
> 
> #top-menu {
>   background-color: #beb500;
>   border-bottom: 1px solid #989100;
>   color: #ffffff;
> }
> 
> #top-menu a {
>   color: #000000;
> }
> 
> #main-menu>ul>li>a.selected {
>     border-bottom: 3px solid #beb500;
> }
> 
> select:focus,
> textarea:focus,
> input[type=datetime]:focus,
> input[type=datetime-local]:focus,
> input[type=date]:focus,
> input[type=month]:focus,
> input[type=time]:focus,
> input[type=week]:focus,
> input[type=number]:focus,
> input[type=url]:focus,
> input[type=tel]:focus,
> input[type=color]:focus,
> input[type=search]:focus,
> input[type=email]:focus,
> input[type=text]:focus,
> input[type=password]:focus {
>     border-color: rgba(167,159,0, .6);
>     box-shadow: inset 0 1px 2px rgba(0, 0, 0, .075), 0 0 0 2px rgba(167,159,0, .2);
> }
> 
> input[type=button],
> input[type=submit],
> input[type=reset],
> button {
>     background-color: #029934;
>     color: #fff;
>     border-color: #029934 #029934 #027b2a;
>     box-shadow: 0 1px 0 #027b2a;
> }
> 
> input[type=button]:hover,
> input[type=button]:focus,
> input[type=submit]:hover,
> input[type=submit]:focus,
> input[type=reset]:hover,
> input[type=reset]:focus,
> button:hover,
> button:focus {
>     background-color: #027b2a;
>     color: #fff;
>     border-color: #027b2a #027b2a #015d1f;
>     box-shadow: 0 1px 0 #015d1f;
> }
> 
> form input[type=submit]+input {
>     background-color: #a3a6b7;
>     color: #fff;
>     border-color: #a3a6b7 #a3a6b7 #5d6560;
>     box-shadow: 0 1px 0 #ababab;
> }
> 
> form input[type=submit]+input:hover,
> form input[type=submit]+input:focus {
>     background-color: #5d6560;
>     color: #fff;
>     border-color: #5d6560 #5d6560 #010101;
>     box-shadow: 0 1px 0 #015d1f;
> }
> 
> p.legend.cal > span {
>   display: flex;
> }
> 
> .issue.details>.subject,
> .issue.details>.author {
>     padding-left: unset;
> }
> 
> .issue.details {
>     margin-top: 5px;
> }
> 
> #login-form {
>   display: none;
> }
> 
> #list-definition > div {
>   display: flex;
>   margin-bottom: 5px;
> }
> 
> #list-definition > div > div {
>   display: inline-grid;
>   margin-right: 5px;
> }
> 
> #list-definition > div > div.buttons {
>   margin-top: auto;
>   margin-bottom: auto;
> }
> 
> #list-definition input[type="button"]:not(:first-child) {
>   margin-top: 5px; /* Mellanrum för alla utom den första */
> }
> 
> #query_form_with_buttons > p.buttons > select {
>   margin-bottom: 5px;
> }
> 
> li.ui-menu-item:hover {
>   background-color: #beb500 !Important;
> }
> 
> .ui-tooltip-content {
>   color: unset !Important;
> }
> .ui-tooltip {
>   box-shadow: unset !Important;
> }
> 
> 
> /* Ticket type colors */
> tr.tracker-1 .id > a,
> tr.tracker-1 .issue_id > a,
> a.tracker-1.issue,
> a.tracker-1,
> .relations > span > a.tracker-1,
> .parent>a.tracker-1 {
> /*
>     background-color: #e5123d;
>     color: #fff;
> */
> }
> 
> tr.tracker-1 .id > a:hover,
> tr.tracker-1 .issue_id > a:hover,
> a.tracker-1.issue:hover,
> a.tracker-1:hover,
> .relations > span > a.tracker-1:hover,
> .parent > a.tracker-1:hover {
> /*
>     background-color: #e5123d;
>     color: #fff;
> */
> }
> 
> label.error {
>   color: #000;
>   text-shadow: 0 0 5px rgba(255, 0, 0, 0.8);
>   animation: pulseShadow 1s infinite;
> }
> 
> /* Definiera keyframes för animationen */
> @keyframes pulseShadow {
>   0%, 100% {
>     text-shadow: 0 0 5px rgba(255, 0, 0, 0.8);
>   }
>   50% {
>     text-shadow: 0 0 15px rgba(255, 0, 0, 1);
>   }
> }
> 
> @media screen and (max-width: 899px) {
>     body #header {
>         background-color: #beb500;
>     }
> }
> 
> @media screen and (max-width: 899px) {
>     body .flyout-menu {
>         background-color: #989100;
>         color: #fff;
>     }
> }
> 
> @media screen and (max-width: 899px) {
>     .flyout-menu {
>         background-color: #706B02;
>     }
> }
> 
> @media screen and (max-width: 899px) {
>     body .flyout-menu h3, body .flyout-menu h4 {
>         border-top: 1px solid #706B02;
>         border-bottom: 1px solid #706B02;
>         background-color: #706B02;
>     }
> }
> ```

thank u so much

**Comment by mt190502** [comment]
> In Redmine version 6.0.0, the current theme appears to be broken.
> <img alt="image" width="1478" src="https://private-user-images.githubusercontent.com/109948984/385131075-1591dc80-1488-4ecf-9849-21126aff452a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM5Njk0ODUsIm5iZiI6MTc0Mzk2OTE4NSwicGF0aCI6Ii8xMDk5NDg5ODQvMzg1MTMxMDc1LTE1OTFkYzgwLTE0ODgtNGVjZi05ODQ5LTIxMTI2YWZmNDUyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQwNlQxOTUzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGJhNTU1NDNmYjBjODU4NTRiZWQyYzhiYmU2YjQ4NzlhMjBiNmIyYzBjNDFkM2ZiNzJjNzk2ZDlmYjc4MTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Z0iylx2LfGY1-rimj7rPVGzAUBjalYV4xpX8_Ycg1VE">

I installed this theme to redmine 6 and I get same issues.
In Redmine 6, I think svg logos are included from Redmine (not from the theme).
And some HTML tags are updated. For example: 

On Redmine 5:
![Image](https://github.com/user-attachments/assets/73de613c-4880-4411-b292-2a248a79cb6b)

On Redmine 6:
![Image](https://github.com/user-attachments/assets/6a69efc3-2553-40ff-b0d7-ed2e3d5a6f8d)

Such changes must also be set on the theme files.

**Comment by kozmotronik** [comment]
I've found out that the broken UI with 3rd party themes issue can be resolved by:

 - executing `bundle exec rake assets:precompile RAILS_ENV=production` in the `REDMINE_ROOT` directory.
 - and then restarting the redmine service or the server.

Source: https://www.redmine.org/issues/42114

**Comment by gagnieray** [comment]
Given that several months have passed since I opened #289 and many others are unanswered, it seems that this theme is unfortunately no longer maintained, or at least not actively maintained. @mrliptontea, do you confirm?

Therefore, I've decided to fork addressing most of the known issues (hopefully), with a complete update of the dependencies and the included components : https://github.com/gagnieray/opale ✨ 🚀 

"So long, and thanks for all the fish!" 🐬 😉

**Comment by mrliptontea** [comment]
@gagnieray I [confirm](https://github.com/mrliptontea/PurpleMine2/issues/258#issuecomment-1363055073), I don't use Redmine anymore and don't have time to maintain this project.

So I agree your new version is the way to go - I'll add a link in this repo's README.

"Don't Panic." 😉
